### ISSUE TITLE
About machine-id

### ISSUE THREAD

**Issue by steakhutzeee** [hotio/duplicacy#1]
Hi,

per my understanding the licenses for Duplicacy are bound to both hostname and machine-id.

So would like to ask, how is generated the machine-id for this container? Could it be possible to let it be customizable via an env? I saw this on another Duplicacy container.

This way it will work also if rebuilt on another device or if something bad happens.

Thanks!

**Comment by mrhotio** [comment]
https://github.com/hotio/duplicacy/blob/50b55d1228158d8f1c704d87806c47fb5f878007/root/etc/cont-init.d/01-config-app#L6

Just make sure the file is there.

**Comment by steakhutzeee** [comment]
> 
> 
> https://github.com/hotio/duplicacy/blob/50b55d1228158d8f1c704d87806c47fb5f878007/root/etc/cont-init.d/01-config-app#L6
> 
> Just make sure the file is there.

Yes, i saw the file there already. But what happens if i use the container on another platform and i want to use the same machine-id?

**Comment by mrhotio** [comment]
If you copy the machine-id and the hostname is the same, nothing should happen...

**Comment by steakhutzeee** [comment]
> 
> 
> If you copy the machine-id and the hostname is the same, nothing should happen...

Ok, so you mean that it's safe to manually edit the machine-id file that is inside the container?

**Comment by mrhotio** [comment]
Why would you edit the file?

**Comment by steakhutzeee** [comment]
> If you copy the machine-id and the hostname is the same, nothing should happen...

The hostname is set in the compose. I see the machine-id in a file inside the compose. From the source you sent it seems to be random, if im not wrong. So copy the machine-in and in case of need put it where?

**Comment by mrhotio** [comment]
Please use discord for basic support questions.
